
CREATE TABLE public.weekly_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    replicate_id INTEGER NOT NULL, 
    growth_cm NUMERIC,          
    stem_mm NUMERIC,            
    leaf_count INTEGER,         
    leaf_length_cm NUMERIC,     
    leaf_width_cm NUMERIC,      
    potential_flower_count INTEGER, 
    current_flower_order INTEGER,   
    accum_ear_count INTEGER,        
    new_grain_count INTEGER,        
    single_grain_g NUMERIC,         
    ear_weight_g NUMERIC,
    brix NUMERIC,                   
    acidity NUMERIC,                
    cracking_rate NUMERIC,
    CONSTRAINT weekly_phenotypes_unique UNIQUE (user_id, year, week, replicate_id)
);
CREATE TABLE public.daily_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE NOT NULL,
    replicate_id INTEGER NOT NULL, 
    year INTEGER, 
    week INTEGER,
    irrigation_ml NUMERIC,          
    reflux_ml NUMERIC,              
    reflux_ec NUMERIC,              
    reflux_ph NUMERIC,
    dripper_count INTEGER,
    irrigation_ec NUMERIC,
    irrigation_ph NUMERIC,
    daily_yield_kg NUMERIC,
    harvest_ear_count INTEGER,
    CONSTRAINT daily_phenotypes_unique UNIQUE (user_id, date, replicate_id)
);
ALTER TABLE public.weekly_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_phenotypes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own weekly phenotypes" ON public.weekly_phenotypes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own daily phenotypes" ON public.daily_phenotypes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX idx_weekly_phenotypes_lookup ON public.weekly_phenotypes (user_id, year, week, replicate_id);
CREATE INDEX idx_daily_phenotypes_lookup ON public.daily_phenotypes (user_id, date, replicate_id);
CREATE INDEX idx_daily_phenotypes_week ON public.daily_phenotypes (user_id, year, week);

