-- 1. 删除旧表（警告：数据将清空）
DROP TABLE IF EXISTS public.weekly_phenotypes;
DROP TABLE IF EXISTS public.daily_phenotypes;
DROP TABLE IF EXISTS public.facility_settings;

-- 2. 创建每周数据表 (weekly_phenotypes) - 使用 sample_name
CREATE TABLE public.weekly_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE,
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    
    project_name TEXT NOT NULL, -- 项目名称（多项目隔离）
    sample_name TEXT NOT NULL, -- 绑定样本名称
    
    -- 手动填报指标 + 自动计算指标 (中文列名)
    "生长量" NUMERIC,
    "茎粗" NUMERIC,
    "叶片总数" NUMERIC,
    "叶长" NUMERIC,
    "叶宽" NUMERIC,
    "潜力开花数" NUMERIC,
    
    "当前开花序数" NUMERIC,
    "单头累计坐果穗数" NUMERIC,
    "单头累计坐果粒数" NUMERIC, -- 自动计算
    "本周单头新增坐果数" NUMERIC,
    "单头总采收果穗数" NUMERIC,
    "本周单头采收果粒数" NUMERIC,
    
    "单粒果重" NUMERIC,
    "单穗重" NUMERIC,
    "单头产量" NUMERIC, -- 自动计算
    "可溶性固形物（糖）" NUMERIC,
    "酸度" NUMERIC,
    
    -- 唯一约束：用户+项目+时间+样本名
    CONSTRAINT weekly_phenotypes_unique UNIQUE (user_id, project_name, year, week, sample_name)
);

-- 3. 创建每日数据表 (daily_phenotypes) - 使用 sample_name
CREATE TABLE public.daily_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE NOT NULL,
    year INTEGER,
    week INTEGER,
    
    project_name TEXT NOT NULL, -- 项目名称（多项目隔离）
    
    -- 中文指标列
    "灌溉量" NUMERIC,
    "回液量" NUMERIC,
    "滴箭个数" NUMERIC,
    "回液比例" NUMERIC,
    "回液EC值" NUMERIC,
    "回液pH值" NUMERIC,
    "灌溉EC" NUMERIC,
    "灌溉pH" NUMERIC,
    "每天产量" NUMERIC,
    "单周产量" NUMERIC,
    "总产量" NUMERIC,
    "温室面积" NUMERIC,
    "单位产量" NUMERIC,
    "报损量" NUMERIC,

    CONSTRAINT daily_phenotypes_unique UNIQUE (user_id, project_name, date)
);

-- 4. 创建温室设置表 (facility_settings)
CREATE TABLE public.facility_settings (
    user_id UUID REFERENCES auth.users NOT NULL,
    "project_name" TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    "滴箭个数" NUMERIC,
    "总滴箭个数" NUMERIC,
    "温室面积" NUMERIC,
    "sample_names" JSONB DEFAULT '[]'::jsonb, -- 预定义的样本名称列表
    
    PRIMARY KEY (user_id, "project_name")
);

-- 5. 开启 RLS
ALTER TABLE public.weekly_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facility_settings ENABLE ROW LEVEL SECURITY;

-- 6. 创建 RLS 策略
CREATE POLICY "Allow authenticated users to select weekly" ON public.weekly_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert weekly" ON public.weekly_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update weekly" ON public.weekly_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete weekly" ON public.weekly_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to select daily" ON public.daily_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert daily" ON public.daily_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update daily" ON public.daily_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete daily" ON public.daily_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage their own settings" ON public.facility_settings 
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 7. 创建触发器函数：自动计算 Weekly 累积指标 (基于 sample_name)
CREATE OR REPLACE FUNCTION update_weekly_calculations()
RETURNS TRIGGER AS $$
DECLARE
    accum_grain NUMERIC;
    accum_yield NUMERIC;
BEGIN
    -- 计算 单头累计坐果粒数
    SELECT COALESCE(SUM("本周单头新增坐果数"), 0)
    INTO accum_grain
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
      AND sample_name = NEW.sample_name
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
    
    NEW."单头累计坐果粒数" := accum_grain + COALESCE(NEW."本周单头新增坐果数", 0);

    -- 计算 单头产量
    SELECT COALESCE(SUM("单穗重"), 0)
    INTO accum_yield
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
      AND sample_name = NEW.sample_name
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
      
    NEW."单头产量" := accum_yield + COALESCE(NEW."单穗重", 0);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 绑定触发器
CREATE TRIGGER trigger_update_weekly_calc
BEFORE INSERT OR UPDATE
ON public.weekly_phenotypes
FOR EACH ROW
EXECUTE FUNCTION update_weekly_calculations();

-- 8. 创建触发器函数：自动计算 Daily 指标
CREATE OR REPLACE FUNCTION update_daily_calculations()
RETURNS TRIGGER AS $$
DECLARE
    v_area NUMERIC;
    v_weekly_sum NUMERIC;
    v_total_sum NUMERIC;
BEGIN
    -- 1. 自动从 facility_settings 读取并填充滴箭个数（如果为 NULL）
    -- 这样用户不需要手动输入，且历史记录保留当时的参数值
    IF NEW."滴箭个数" IS NULL THEN
        SELECT "滴箭个数" INTO NEW."滴箭个数"
        FROM public.facility_settings
        WHERE user_id = NEW.user_id 
          AND "project_name" = NEW.project_name;
    END IF;

    -- 2. 计算 回液比例 = 回液量 / (灌溉量 * 滴箭个数) * 100
    -- 使用 daily_phenotypes 中已保存的滴箭个数值
    IF NEW."灌溉量" IS NOT NULL AND NEW."灌溉量" > 0 
       AND NEW."回液量" IS NOT NULL
       AND NEW."滴箭个数" IS NOT NULL AND NEW."滴箭个数" > 0 THEN
        NEW."回液比例" := (NEW."回液量" / (NEW."灌溉量" * NEW."滴箭个数")) * 100;
    ELSE
        NEW."回液比例" := NULL;
    END IF;

    -- 3. 计算 单周产量 = 本周每天累计产量求和
    IF NEW."每天产量" IS NOT NULL THEN
        SELECT COALESCE(SUM("每天产量"), 0) INTO v_weekly_sum
        FROM public.daily_phenotypes
        WHERE user_id = NEW.user_id 
          AND project_name = NEW.project_name
          AND year = NEW.year 
          AND week = NEW.week
          AND date != NEW.date;
          
        NEW."单周产量" := v_weekly_sum + NEW."每天产量";

        -- 4. 计算 总产量 = 所有每天产量求和
        SELECT COALESCE(SUM("每天产量"), 0) INTO v_total_sum
        FROM public.daily_phenotypes
        WHERE user_id = NEW.user_id
            AND project_name = NEW.project_name
            AND date != NEW.date;
        
        NEW."总产量" := v_total_sum + NEW."每天产量";

        -- 5. 计算 单位产量 = 总产量 / 温室面积
        -- 从 facility_settings 实时读取温室面积（不保存快照）
        SELECT "温室面积" INTO v_area
        FROM public.facility_settings
        WHERE user_id = NEW.user_id 
          AND "project_name" = NEW.project_name;
          
        IF v_area IS NOT NULL AND v_area > 0 THEN
            NEW."单位产量" := NEW."总产量" / v_area;
        ELSE
            NEW."单位产量" := NULL;
        END IF;
    ELSE
        NEW."单周产量" := NULL;
        NEW."总产量" := NULL;
        NEW."单位产量" := NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 绑定触发器
CREATE TRIGGER trigger_update_daily_calc
BEFORE INSERT OR UPDATE
ON public.daily_phenotypes
FOR EACH ROW
EXECUTE FUNCTION update_daily_calculations();

-- 9. 创建触发器：当温室参数更新时，自动更新 daily_phenotypes
CREATE OR REPLACE FUNCTION recalc_today_daily_on_settings_change()
RETURNS TRIGGER AS $$
DECLARE
    today_date DATE;
BEGIN
    -- 获取北京时间的今天日期 (UTC+8)
    today_date := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')::DATE;
    
    -- 当滴箭个数变化时：只更新当天的记录（保留历史快照）
    -- 当温室面积变化时：重新计算所有记录的单位产量
    IF TG_OP = 'UPDATE' AND (OLD."滴箭个数" IS DISTINCT FROM NEW."滴箭个数") THEN
        -- 滴箭个数变化：只更新当天的快照值
        UPDATE public.daily_phenotypes
        SET "滴箭个数" = NEW."滴箭个数"
        WHERE user_id = NEW.user_id 
          AND project_name = NEW."project_name"
          AND date = today_date;
          
    ELSIF TG_OP = 'UPDATE' AND (OLD."温室面积" IS DISTINCT FROM NEW."温室面积") THEN
        -- 温室面积变化：强制重新计算【所有记录】的单位产量
        -- 触发器会使用最新的温室面积值
        UPDATE public.daily_phenotypes
        SET "灌溉量" = "灌溉量"  -- 触发 update_daily_calculations
        WHERE user_id = NEW.user_id 
          AND project_name = NEW."project_name";
          -- 注意：这里不限制 date，所以会更新所有历史记录
          
    ELSIF TG_OP = 'INSERT' THEN
        -- 新项目：不需要特殊处理
        NULL;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 绑定触发器
CREATE TRIGGER trigger_recalc_today_on_settings_update
AFTER INSERT OR UPDATE OF "滴箭个数", "温室面积"
ON public.facility_settings
FOR EACH ROW
EXECUTE FUNCTION recalc_today_daily_on_settings_change();

-- 10. 创建删除数据的 RPC 函数 (按名称删除)
CREATE OR REPLACE FUNCTION delete_sample_data(target_sample_name TEXT)
RETURNS VOID AS $$
BEGIN
    DELETE FROM public.weekly_phenotypes 
    WHERE user_id = auth.uid() AND sample_name = target_sample_name;
    
    DELETE FROM public.daily_phenotypes 
    WHERE user_id = auth.uid() AND sample_name = target_sample_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
