-- SQL Script to create database tables
-- Run this in your Supabase SQL Editor

-- EXPLANATION OF DATA MODEL:
-- phenotype_records: 存储每个样本的采集数据（30个样本/周 = 30行/周）
-- weekly_statistics: 存储基于所有样本计算的统计指标（1行/周）

-- =============================================
-- Table 1: phenotype_records (采集数据表)
-- =============================================
-- 每行 = 1个样本 × 1周的数据
CREATE TABLE public.phenotype_records (
    -- System Columns
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Time Dimensions
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    date DATE NOT NULL,
    
    -- Replicate Dimension (样本编号: 1-30)
    replicate_id INTEGER NOT NULL CHECK (replicate_id BETWEEN 1 AND 50), 

    -- =============================================
    -- Collection Indicators (采集指标)
    -- =============================================

    -- Growth Traits (生长指标)
    growth_cm NUMERIC,          
    stem_mm NUMERIC,            
    leaf_count INTEGER,         
    leaf_length_cm NUMERIC,     
    leaf_width_cm NUMERIC,      
    
    -- Flowering & Fruiting Traits (开花坐果指标)
    potential_flower_count INTEGER, 
    current_flower_order INTEGER,   
    accum_ear_count INTEGER,        
    new_grain_count INTEGER,        
    
    -- Yield Traits (产量指标)
    weekly_yield_kg NUMERIC,            
    single_grain_g NUMERIC,         
    new_harvest_grain_count INTEGER,    
    ear_weight_g NUMERIC,
    
    -- Fruit Quality Traits (品质指标)
    brix NUMERIC,                   
    acidity NUMERIC,                
    cracking_rate NUMERIC,          
    
    -- Environment & Management (环境管理指标)
    irrigation_ml NUMERIC,          
    reflux_ml NUMERIC,              
    reflux_ec NUMERIC,              
    reflux_ph NUMERIC,
    dripper_count INTEGER,

    -- Constraint: 每个用户、每周、每个样本只能有一条记录
    CONSTRAINT phenotype_records_pk_unique UNIQUE (user_id, year, week, replicate_id)
);

-- Enable RLS
ALTER TABLE public.phenotype_records ENABLE ROW LEVEL SECURITY;

-- Create Policy
CREATE POLICY "Users can manage their own phenotype records" 
ON public.phenotype_records
FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create Index
CREATE INDEX idx_phenotype_records_year_week ON public.phenotype_records (user_id, year, week);
CREATE INDEX idx_phenotype_records_replicate ON public.phenotype_records (user_id, year, week, replicate_id);


-- =============================================
-- Table 2: weekly_statistics (统计指标表)
-- =============================================
-- 每行 = 1周的统计数据（基于30个样本计算）
CREATE TABLE public.weekly_statistics (
    -- System Columns
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Time Dimensions
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    date DATE NOT NULL,
    
    -- =============================================
    -- Statistical Indicators (统计指标)
    -- 这些指标是根据30个样本和历史数据计算得出
    -- =============================================
    
    -- 累积统计
    accum_grain_count NUMERIC,          -- 单头累计坐果粒数（累加所有周的new_grain_count）
    total_yield_kg NUMERIC,             -- 总产量（累加所有周的weekly_yield_kg）
    total_harvest_ear_count INTEGER,    -- 单头总采收果穗数
    single_head_yield_g NUMERIC,        -- 单头产量（累加所有周的ear_weight_g）
    
    -- 配置参数（每周可能不同）
    greenhouse_area_m2 NUMERIC,         -- 温室面积
    
    -- 计算指标
    unit_yield NUMERIC,                 -- 单位产量 = total_yield_kg / greenhouse_area_m2
    reflux_ratio NUMERIC,               -- 回液比例 = 平均(reflux_ml / (irrigation_ml * dripper_count))
    
    -- Constraint: 每个用户、每周只能有一条统计记录
    CONSTRAINT weekly_statistics_pk_unique UNIQUE (user_id, year, week)
);

-- Enable RLS
ALTER TABLE public.weekly_statistics ENABLE ROW LEVEL SECURITY;

-- Create Policy
CREATE POLICY "Users can manage their own statistics" 
ON public.weekly_statistics
FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create Index
CREATE INDEX idx_weekly_statistics_year_week ON public.weekly_statistics (user_id, year, week);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_weekly_statistics_updated_at
    BEFORE UPDATE ON public.weekly_statistics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
