-- SQL Script to create database tables
-- Run this in your Supabase SQL Editor

-- EXPLANATION OF DATA MODEL:
-- phenotype_records: 存储每个样本的采集数据（30个样本/周 = 30行/周）
-- weekly_statistics: 存储基于所有样本计算的统计指标（1行/周）

-- =============================================
-- Table 1: phenotype_records (采集数据表)
-- =============================================
-- 每行 = 1个样本 × 1周的数据
-- =============================================
-- Table 1: weekly_phenotypes (每周采集数据)
-- =============================================
-- 每行 = 1个样本 × 1周
CREATE TABLE public.weekly_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Dimensions
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    replicate_id INTEGER NOT NULL, 

    -- Weekly Indicators
    growth_cm NUMERIC,          
    stem_mm NUMERIC,            
    leaf_count INTEGER,         
    leaf_length_cm NUMERIC,     
    leaf_width_cm NUMERIC,      
    potential_flower_count INTEGER, 
    current_flower_order INTEGER,   
    accum_ear_count INTEGER,        
    new_grain_count INTEGER,        
    single_grain_g NUMERIC,         
    ear_weight_g NUMERIC,
    brix NUMERIC,                   
    acidity NUMERIC,                
    cracking_rate NUMERIC,

    -- Constraint: Unique per user, week, replicate
    CONSTRAINT weekly_phenotypes_unique UNIQUE (user_id, year, week, replicate_id)
);

-- =============================================
-- Table 2: daily_phenotypes (每日采集数据)
-- =============================================
-- 每行 = 1个样本 × 1天
CREATE TABLE public.daily_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Dimensions
    date DATE NOT NULL,
    replicate_id INTEGER NOT NULL, 
    
    -- Redundant time columns for easier querying (Optional, but helpful)
    year INTEGER, 
    week INTEGER,

    -- Daily Indicators
    irrigation_ml NUMERIC,          
    reflux_ml NUMERIC,              
    reflux_ec NUMERIC,              
    reflux_ph NUMERIC,
    dripper_count INTEGER,
    irrigation_ec NUMERIC,
    irrigation_ph NUMERIC,
    daily_yield_kg NUMERIC,
    harvest_ear_count INTEGER,

    -- Constraint: Unique per user, date, replicate
    CONSTRAINT daily_phenotypes_unique UNIQUE (user_id, date, replicate_id)
);

-- Enable RLS
ALTER TABLE public.weekly_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_phenotypes ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can manage their own weekly phenotypes" ON public.weekly_phenotypes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own daily phenotypes" ON public.daily_phenotypes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Create Indexes
CREATE INDEX idx_weekly_phenotypes_lookup ON public.weekly_phenotypes (user_id, year, week, replicate_id);
CREATE INDEX idx_daily_phenotypes_lookup ON public.daily_phenotypes (user_id, date, replicate_id);
CREATE INDEX idx_daily_phenotypes_week ON public.daily_phenotypes (user_id, year, week);


-- =============================================
-- Table 2: weekly_statistics (统计指标表)
-- =============================================
-- 每行 = 1周的统计数据（基于30个样本计算）
CREATE TABLE public.weekly_statistics (
    -- System Columns
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Time Dimensions
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    date DATE NOT NULL,
    
    -- =============================================
    -- Statistical Indicators (统计指标)
    -- 这些指标是根据30个样本和历史数据计算得出
    -- =============================================
    
    -- 累积统计
    accum_grain_count NUMERIC,          -- 单头累计坐果粒数（累加所有周的new_grain_count）
    total_yield_kg NUMERIC,             -- 总产量（累加所有周的weekly_yield_kg）
    total_harvest_ear_count INTEGER,    -- 单头总采收果穗数
    single_head_yield_g NUMERIC,        -- 单头产量（累加所有周的ear_weight_g）
    
    -- 配置参数（每周可能不同）
    greenhouse_area_m2 NUMERIC,         -- 温室面积
    
    -- 计算指标
    unit_yield NUMERIC,                 -- 单位产量 = total_yield_kg / greenhouse_area_m2
    reflux_ratio NUMERIC,               -- 回液比例 = 平均(reflux_ml / (irrigation_ml * dripper_count))
    
    -- Constraint: 每个用户、每周只能有一条统计记录
    CONSTRAINT weekly_statistics_pk_unique UNIQUE (user_id, year, week)
);

-- Enable RLS
ALTER TABLE public.weekly_statistics ENABLE ROW LEVEL SECURITY;

-- Create Policy
CREATE POLICY "Users can manage their own statistics" 
ON public.weekly_statistics
FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create Index
CREATE INDEX idx_weekly_statistics_year_week ON public.weekly_statistics (user_id, year, week);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_weekly_statistics_updated_at
    BEFORE UPDATE ON public.weekly_statistics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
