-- 1. 删除旧表（警告：数据将清空）
DROP TABLE IF EXISTS public.weekly_phenotypes;
DROP TABLE IF EXISTS public.daily_phenotypes;

-- 2. 创建每周数据表 (weekly_phenotypes)
CREATE TABLE public.weekly_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    replicate_id INTEGER NOT NULL,
    
    -- 手动填报指标 + 自动计算指标
    "生长量" NUMERIC,
    "茎粗" NUMERIC,
    "叶片总数" NUMERIC,
    "叶长" NUMERIC,
    "叶宽" NUMERIC,
    
    "当前开花序数" NUMERIC,
    "单头累计坐果穗数" NUMERIC,
    "单头累计坐果粒数" NUMERIC, -- 自动计算: SUM(本周单头新增坐果数)
    "本周单头新增坐果数" NUMERIC,
    "单头总采收果穗数" NUMERIC, -- 暂时作为手动填报项 (如果需要自动计算请后续修改)
    "本周单头采收果粒数" NUMERIC,
    
    "单粒果重" NUMERIC,
    "单穗重" NUMERIC,
    "单头产量" NUMERIC, -- 自动计算: SUM(单穗重)
    "可溶性固形物（糖）" NUMERIC,
    "酸度" NUMERIC,
    
    CONSTRAINT weekly_phenotypes_unique UNIQUE (user_id, year, week, replicate_id)
);

-- 3. 创建每日数据表 (daily_phenotypes)
CREATE TABLE public.daily_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE NOT NULL,
    year INTEGER,
    week INTEGER,
    replicate_id INTEGER NOT NULL,
    
    -- 中文指标列
    "灌溉量" NUMERIC,
    "回液量" NUMERIC,
    "滴箭个数" NUMERIC,
    "回液比例" NUMERIC,
    "回液EC值" NUMERIC,
    "回液pH值" NUMERIC,
    "灌溉EC" NUMERIC,
    "灌溉pH" NUMERIC,
    "每天产量" NUMERIC,
    "单周产量" NUMERIC,
    "总产量" NUMERIC,
    "温室面积" NUMERIC,
    "单位产量" NUMERIC,
    "报损量" NUMERIC,

    CONSTRAINT daily_phenotypes_unique UNIQUE (user_id, date, replicate_id)
);

-- 4. 开启 RLS
ALTER TABLE public.weekly_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_phenotypes ENABLE ROW LEVEL SECURITY;

-- 5. 创建通用读写策略
CREATE POLICY "Allow authenticated users to select weekly" ON public.weekly_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert weekly" ON public.weekly_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update weekly" ON public.weekly_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete weekly" ON public.weekly_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to select daily" ON public.daily_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert daily" ON public.daily_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update daily" ON public.daily_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete daily" ON public.daily_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

-- 6. 创建触发器函数：自动计算累积指标
CREATE OR REPLACE FUNCTION update_weekly_calculations()
RETURNS TRIGGER AS $$
DECLARE
    accum_grain NUMERIC;
    accum_yield NUMERIC;
BEGIN
    -- 计算 单头累计坐果粒数 = SUM(本周单头新增坐果数)
    SELECT COALESCE(SUM("本周单头新增坐果数"), 0)
    INTO accum_grain
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
      AND replicate_id = NEW.replicate_id
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
    
    NEW."单头累计坐果粒数" := accum_grain + COALESCE(NEW."本周单头新增坐果数", 0);

    -- 计算 单头产量 = SUM(单穗重)
    SELECT COALESCE(SUM("单穗重"), 0)
    INTO accum_yield
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
      AND replicate_id = NEW.replicate_id
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
      
    NEW."单头产量" := accum_yield + COALESCE(NEW."单穗重", 0);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. 绑定触发器
CREATE TRIGGER trigger_update_weekly_calc
BEFORE INSERT OR UPDATE
ON public.weekly_phenotypes
FOR EACH ROW
EXECUTE FUNCTION update_weekly_calculations();
