-- 1. 删除旧表（警告：数据将清空）
DROP TABLE IF EXISTS public.weekly_phenotypes;
DROP TABLE IF EXISTS public.daily_phenotypes;

-- 2. 创建每周数据表 (weekly_phenotypes)
CREATE TABLE public.weekly_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    "project_name" TEXT, -- 项目名称 (如: 翠湖温室)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    replicate_id INTEGER NOT NULL DEFAULT 1, -- 本周第几条记录（自动计算）
    "sample_name" TEXT, -- 样本名称（实际标识符）
    
    -- 手动填报指标 + 自动计算指标
    "生长量" NUMERIC,
    "茎粗" NUMERIC,
    "叶片总数" NUMERIC,
    "叶长" NUMERIC,
    "叶宽" NUMERIC,
    
    "当前开花序数" NUMERIC,
    "单头累计坐果穗数" NUMERIC,
    "单头累计坐果粒数" NUMERIC, -- 自动计算: SUM(本周单头新增坐果数)
    "本周单头新增坐果数" NUMERIC,
    "单头总采收果穗数" NUMERIC, -- 暂时作为手动填报项 (如果需要自动计算请后续修改)
    "本周单头采收果粒数" NUMERIC,
    
    "单粒果重" NUMERIC,
    "单穗重" NUMERIC,
    "单头产量" NUMERIC, -- 自动计算: SUM(单穗重)
    "可溶性固形物（糖）" NUMERIC,
    "酸度" NUMERIC,
    
    CONSTRAINT weekly_phenotypes_unique UNIQUE (user_id, year, week, "sample_name")
);

-- 3. 创建每日数据表 (daily_phenotypes)
CREATE TABLE public.daily_phenotypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    "project_name" TEXT DEFAULT '翠湖温室', -- Add project name for daily data too
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE NOT NULL,
    year INTEGER,
    week INTEGER,
    replicate_id INTEGER NOT NULL DEFAULT 1, -- 行计数器，仅表示第几条记录
    
    -- 中文指标列
    "灌溉量" NUMERIC,
    "回液量" NUMERIC,

    "回液比例" NUMERIC,
    "回液EC值" NUMERIC,
    "回液pH值" NUMERIC,
    "灌溉EC" NUMERIC,
    "灌溉pH" NUMERIC,
    
    "每天产量" NUMERIC,
    "单周产量" NUMERIC,
    "总产量" NUMERIC,

    "单位产量" NUMERIC,
    "报损量" NUMERIC,

    CONSTRAINT daily_phenotypes_unique UNIQUE (user_id, date, "project_name")
);

-- 4. 开启 RLS
ALTER TABLE public.weekly_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_phenotypes ENABLE ROW LEVEL SECURITY;

-- 5. 创建通用读写策略
CREATE POLICY "Allow authenticated users to select weekly" ON public.weekly_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert weekly" ON public.weekly_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update weekly" ON public.weekly_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete weekly" ON public.weekly_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to select daily" ON public.daily_phenotypes FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to insert daily" ON public.daily_phenotypes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to update daily" ON public.daily_phenotypes FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to delete daily" ON public.daily_phenotypes FOR DELETE USING (auth.role() = 'authenticated');

-- 6. 创建触发器函数：自动计算累积指标 (Weekly)
CREATE OR REPLACE FUNCTION update_weekly_calculations()
RETURNS TRIGGER AS $$
DECLARE
    accum_grain NUMERIC;
    accum_yield NUMERIC;
BEGIN
    -- 计算 单头累计坐果粒数 = SUM(本周单头新增坐果数)
    SELECT COALESCE(SUM("本周单头新增坐果数"), 0)
    INTO accum_grain
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
        -- 统计计算基于 sample_name 而非 replicate_id
      AND "sample_name" = NEW."sample_name"
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
    
    NEW."单头累计坐果粒数" := accum_grain + COALESCE(NEW."本周单头新增坐果数", 0);

    -- 计算 单头产量 = SUM(单穗重)
    SELECT COALESCE(SUM("单穗重"), 0)
    INTO accum_yield
    FROM public.weekly_phenotypes
    WHERE user_id = NEW.user_id
      -- 统计计算基于 sample_name 而非 replicate_id
      AND "sample_name" = NEW."sample_name"
      AND (year < NEW.year OR (year = NEW.year AND week < NEW.week));
      
    NEW."单头产量" := accum_yield + COALESCE(NEW."单穗重", 0);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. 绑定触发器 (Weekly)
CREATE TRIGGER trigger_update_weekly_calc
BEFORE INSERT OR UPDATE
ON public.weekly_phenotypes
FOR EACH ROW
EXECUTE FUNCTION update_weekly_calculations();

-- 7.5 创建触发器函数：自动计算 replicate_id (本周该样本的第几条记录)
CREATE OR REPLACE FUNCTION set_weekly_replicate_id()
RETURNS TRIGGER AS $$
DECLARE
    current_count INTEGER;
BEGIN
    -- 仅对 INSERT 操作自动计算
    IF TG_OP = 'INSERT' THEN
        -- 计算当前用户、项目、年、周、样本内已有多少记录
        SELECT COUNT(*) INTO current_count
        FROM public.weekly_phenotypes
        WHERE user_id = NEW.user_id
          AND "project_name" = NEW."project_name"
          AND "sample_name" = NEW."sample_name"
          AND year = NEW.year
          AND week = NEW.week;
        
        NEW.replicate_id := current_count + 1;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 绑定 replicate_id 触发器 (Weekly)
CREATE TRIGGER trigger_set_weekly_replicate_id
BEFORE INSERT
ON public.weekly_phenotypes
FOR EACH ROW
EXECUTE FUNCTION set_weekly_replicate_id();

-- 8. 创建温室设置表 (facility_settings)
-- 注意：重建表以支持多项目 (user_id, project_name) 作为主键
DROP TABLE IF EXISTS public.facility_settings;
CREATE TABLE public.facility_settings (
    user_id UUID REFERENCES auth.users NOT NULL,
    "project_name" TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    "滴箭个数" NUMERIC,
    "温室面积" NUMERIC,
    "sample_names" JSONB DEFAULT '[]'::jsonb, -- 预定义的样本名称列表
    
    PRIMARY KEY (user_id, "project_name")
);

-- RLS
ALTER TABLE public.facility_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own settings" ON public.facility_settings 
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 9. 创建触发器函数：自动计算每日指标 (Daily)
-- 计算: 回液比例, 单周产量, 总产量, 单位产量
CREATE OR REPLACE FUNCTION update_daily_calculations()
RETURNS TRIGGER AS $$
DECLARE
    v_dripper_count NUMERIC;
    v_area NUMERIC;
    v_weekly_sum NUMERIC;
    v_total_sum NUMERIC;
BEGIN
    -- 1. 获取温室参数
    -- 注意: 需要根据 user_id 和 project_name 获取
    -- daily_phenotypes 目前没有 project_name 字段? 
    -- 等等，weekly 加了 project_name，daily 还没加！
    -- 如果是 daily data，必须知道属于哪个 project 才能查到 area。
    -- user 请求: "所有后面采集的数据都会在当前项目下"。
    -- 所以 daily_phenotypes 也必须加 project_name, 且作为唯一约束的一部分。
    
    SELECT "滴箭个数", "温室面积" INTO v_dripper_count, v_area
    FROM public.facility_settings
    WHERE user_id = NEW.user_id 
      AND "project_name" = NEW."project_name"; -- Now required

    -- 2. 计算 回液比例 = 回液量 / (灌溉量 * 滴箭个数)
    -- 注意: 结果转为百分比 (0-70)
    -- 如果条件不满足，保持 NULL 而非设为 0
    IF NEW."灌溉量" IS NOT NULL AND NEW."灌溉量" > 0 
       AND NEW."回液量" IS NOT NULL
       AND v_dripper_count IS NOT NULL AND v_dripper_count > 0 THEN
        NEW."回液比例" := (NEW."回液量" / (NEW."灌溉量" * v_dripper_count)) * 100;
    ELSE
        NEW."回液比例" := NULL;
    END IF;

    -- 3. 计算 单周产量 = 本周每天累计产量求和
    -- 注意: 需要包含当前正在插入的行 (所以是 历史本周 + 当前值)
    -- 且必须是同项目
    -- 如果每天产量为 NULL，不计算
    IF NEW."每天产量" IS NOT NULL THEN
        SELECT COALESCE(SUM("每天产量"), 0) INTO v_weekly_sum
        FROM public.daily_phenotypes
        WHERE user_id = NEW.user_id 
          AND "project_name" = NEW."project_name"
          AND year = NEW.year 
          AND week = NEW.week
          AND date != NEW.date; -- 排除自身(如果是更新)
          
        NEW."单周产量" := v_weekly_sum + NEW."每天产量";

        -- 4. 计算 总产量 = 所有每天产量求和
        SELECT COALESCE(SUM("每天产量"), 0) INTO v_total_sum
        FROM public.daily_phenotypes
        WHERE user_id = NEW.user_id
            AND "project_name" = NEW."project_name"
            AND date != NEW.date; -- 排除自身
        
        NEW."总产量" := v_total_sum + NEW."每天产量";

        -- 5. 计算 单位产量 = 总产量 / 温室面积
        IF v_area IS NOT NULL AND v_area > 0 THEN
            NEW."单位产量" := NEW."总产量" / v_area;
        ELSE
            NEW."单位产量" := NULL;
        END IF;
    ELSE
        NEW."单周产量" := NULL;
        NEW."总产量" := NULL;
        NEW."单位产量" := NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 10. 绑定触发器 (Daily)
CREATE TRIGGER trigger_update_daily_calc
BEFORE INSERT OR UPDATE
ON public.daily_phenotypes
FOR EACH ROW
EXECUTE FUNCTION update_daily_calculations();

-- 11. 创建触发器：当 facility_settings 更新时，自动重新计算当天的 daily_phenotypes
CREATE OR REPLACE FUNCTION recalc_today_daily_on_settings_change()
RETURNS TRIGGER AS $$
DECLARE
    today_date DATE;
BEGIN
    -- 获取北京时间的今天日期 (UTC+8)
    today_date := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')::DATE;
    
    -- 通过更新一个已有值来触发 BEFORE UPDATE 触发器重新计算
    UPDATE public.daily_phenotypes
    SET "灌溉量" = "灌溉量"
    WHERE user_id = NEW.user_id 
      AND "project_name" = NEW."project_name"
      AND date = today_date;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 绑定触发器 (Facility Settings)
CREATE TRIGGER trigger_recalc_today_on_settings_update
AFTER INSERT OR UPDATE OF "滴箭个数", "温室面积"
ON public.facility_settings
FOR EACH ROW
EXECUTE FUNCTION recalc_today_daily_on_settings_change();
